### PR TITLE
add domain and loggedonusers to sysinfo

### PR DESCRIPTION
**Pull request by dmaloney-r7**
added the domain name and logged on user counts
to the sysinfo command

MSP-12715

Follow Verification Steps for https://github.com/rapid7/metasploit-framework/pull/5352

### CODE REVIEW

**Comment by bcook-r7** [comment]
jenkins, this is ok to test

**Comment by bcook-r7** [comment]
jenkins, add to whitelist

**Comment by bcook-r7** [comment]
I can fix this up.

**Comment by busterb** [comment]
```
meterpreter > sysinfo
Computer        : MSF-DEV
OS              : Windows 8 (Build 9200).
Architecture    : x64 (Current Process is WOW64)
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
```

**Comment by busterb** [comment]
Fixup commit: 17fc25a17f50fe8dd048057762e3dac535fee036

**Pull request merged**
