### PR TITLE
Implement support for ssl cert verify toggling

### PR DESCRIPTION
**Pull request by OJ**
This PR contains the Meterpreter-side of the MSF PR that implements SSL certificate verification toggling. Full details of the concept/etc, along with how to test/validate can be found over there.

The MSF PR is: https://github.com/rapid7/metasploit-framework/pull/5081

### Stuff done in this PR

* Implemented get/set command for ssl certificate verification. This obviously only applies to transports that are HTTPS as this point, though later on we might be able to add it for tcp too.
* Updated the transport switching command name/function so that it's in sync with these changes.
* Did some code tidying and refactoring.

### Verification

- [ ] Windows payloads still build cleanly.
- [ ] Posix payloads still build cleanly.
- [ ] All the stuff in the MSF PR works.

### Sample runs

Please see the MSF PR.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Somehow all of the EOL characters changed in source/server/server_setup_win.c between this and master.

**Comment by OJ** [comment]
Crap :(

**Comment by OJ** [comment]
I'm not sure what's going on here. The line endings for the file are definitely right now (using the Windows CRLF style like the rest of them), but github thinks that the line endings have all changed.

Totally confused.

**Comment by kernelsmith** [comment]
Git config has a setting for controlling the line sirltuation, maybe that got changed?

**Comment by OJ** [comment]
It hasn't changed on any of my setups for about 4 years :)

**Comment by bcook-r7** [comment]
thanks for the update, lets get a gem build going.

**Pull request merged**
