### PR TITLE
Feature meterp sniffer wpcap

### PR DESCRIPTION
**Pull request by sempervictus**
Convert sniffer to use WinPCAP instead of PSSDK. Allows community members to build their own sniffers, and more. See commit messages for details and test output.

### CODE REVIEW

**Comment by OJ** [comment]
jenkins, this is ok to test

**Comment by bcook-r7** [comment]
We'll need to also incorporate winpcap's libs and headers into the windows build process I presume. That would probably mean an addition to the meterpreter-deps repo, like we do for openssl.

**Comment by sempervictus** [comment]
The updated sniffer extension already expects winpcap to be here, i'd obviously appreciate any extra testing, but i believe it should build as is on the windows side.

**Comment by sempervictus** [comment]
Looks like i broke the POSIX side pretty badly.
@bcook-r7, @OJ : could you guys take a look at what i broke? Seems some of my declarations dont add up on the POSIX side.

**Comment by OJ** [comment]
@sempervictus it could be that the build isn't picking up the deps properly. I'll have a poke shortly.

**Comment by sempervictus** [comment]
The POSIX side already has all the deps it needs, and i'm failing the build locally as well on 14.04. I can spin up a build host later, but i'm elbow deep in a stack of documentation.

**Comment by OJ** [comment]
Ah ok mate, no worries.

**Comment by hsluoyz** [comment]
Hi.

You would like to try Npcap: https://github.com/nmap/npcap.

It's another fork of WinPcap with multiple new features.

**Comment by sempervictus** [comment]
We did, I think the momentum behind opening up all extensions may have
fizzled though or the timing of this PR against the migration to payloads
repo left it behind. Would love to see it fixed for POSIX and in full review

**Comment by bcook-r7** [comment]
It more-or-less got left behind, but definitely still interested if someone wants to rebase this on the new repo!

**Comment by bcook-r7** [comment]
cc @wwebb-r7

**Comment by wwebb-r7** [comment]
@bcook-r7 started seriously looking into it as of today

**Comment by busterb** [comment]
Closing this out since this repo is dead.

**Pull request closed without merging**
