### PR TITLE
Add stageless meterpreter payload support

### PR DESCRIPTION
**Pull request by OJ**
For all the detail, please see the MSF side of this PR: https://github.com/rapid7/metasploit-framework/pull/4925

Given that the MSF side of this PR is required to do the testing that's where all the details are. Sorry for the scant detail here, but I felt that keeping it in the one spot made the most sense.

Note: there are a few formatting changes, style updates, documentation updates, etc in here. I realised later in the game that some of this might overlap with the changes that @bcook-r7 is making in his effort to replace openssl with libressl. Happy to help with the merging of that effort (sorry for any merge conflicts for you Brent).

Thanks!

### CODE REVIEW

**Comment by bcook-r7** [comment]
No sweat! To the first merger lands the spoils!

**Comment by bcook-r7** [comment]
By the way, I'm fixing the posix build failure here, doing a little rearranging to make it nice. I'll send a PR when its done.

**Comment by OJ** [comment]
The POSIX build failed? Crap! Thanks for the help Brent!

**Comment by busterb** [comment]
I went a little too far with refactoring though. Let me reel it in and send you what I had earlier that duplicates code a little, but gets us over this hump for this PR.

**Comment by busterb** [comment]
https://github.com/OJ/meterpreter/pull/4

**Comment by OJ** [comment]
Thanks @bcook-r7 ! I'll look at this first thing.

**Comment by bcook-r7** [comment]
Looking good on this side, no regressions. I'll land so we can build a test gem.

**Comment by OJ** [comment]
Awesome, thanks @bcook-r7 !

**Pull request merged**
