### PR TITLE
Improve linux migrate reliability

### PR DESCRIPTION
**Pull request by jvazquez-r7**
Some fixes for the linux migrate. The important thing, adding a nop slide to a call stub. Patching EIP with ptrace is even more dangerous thane expected :\ I am not sure 100% of the reliability problems, maybe memory alignments :?

Anyway, on my tests it makes linux migrate more reliable than the initial version. Still a "dangerous" feature, but better I think :)

Verification
---------------

- [x] make new builds with these changes
- [x] Verify you can get a linux a linux meterpreter session
- [x] Verify you can migrate (limitations and steps here: https://github.com/rapid7/metasploit-framework/pull/3594). If you want to make things easy try linux 32 bits without ptrace restrictions, for example, Ubuntu 10.04 32 bits.
- [x] Make a pull request for metasploit-framework with fresh binaries and ping me, I can help to verify land them if you need :) (If you need fresh binaries to help with verification just let me know!)

### CODE REVIEW

**Comment by bcook-r7** [comment]
Taking a look now.

**Comment by bcook-r7** [comment]
Well, after a couple of attempts, I cannot get this to run properly with locally-built binaries. I think I must have been testing your binaries the whole time with PR #93. I have to head out for now, but will be back later to debug, if someone doesn't look at this first.

**Comment by jvazquez-r7** [comment]
@bcook-r7, if you would like I could make a PR to metasploit-framework with my built binaries to help with testing! But I would encourage new binaries and PR to metasploit-framework once this PR review is finished :)

**Comment by bcook-r7** [comment]
It seems that there is some protection in the compiler I was using that breaks meterpreter with the latest Ubuntu. I rebuilt with 10.04.4 i386 and it worked like a charm:

```
meterpreter > ps
...
 55994  48270  server                   0        bcook       ../metasploit-framework/server
 56009  44199  bash                     0        bcook       -bash
 56094  56009  dummy                    0        bcook       ./dummy

meterpreter > migrate 56094
[*] Migrating to 56094
[*] Migration completed successfully.
meterpreter > sysinfo
Computer     : mint
OS           : Linux mint 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 (x86_64)
Architecture : x86_64
Meterpreter  : x86/linux
meterpreter > ps
...
 55994  48270  [server] <defunct>        0        bcook
 56009  44199  bash                      0        bcook       -bash
 56094  56009  dummy                     0        bcook       ./dummy


meterpreter >
```

**Comment by bcook-r7** [comment]
I was able to migrate between gnome-terminal and update-notifier, leaving a nice trail of destruction in my wake:

```
 9619   1      gnome-terminal           0        bcook       gnome-terminal
 9624   9619   gnome-pty-helpe          0        bcook       gnome-pty-helper
 9625   9619   bash                     0        bcook       bash
 9641   1      unity-scope-vid          0        bcook       /usr/bin/python /usr/lib/unity-scope-video-remote/unity-scope-video-remote
 9702   9237   gdu-notificatio          0        bcook       /usr/lib/gnome-disk-utility/gdu-notification-daemon
 9707   9237   telepathy-indic          0        bcook       telepathy-indicator
 9713   1      mission-control          0        bcook       /usr/lib/telepathy/mission-control-5
 9718   1      goa-daemon               0        bcook       /usr/lib/gnome-online-accounts/goa-daemon
 9725   9237   gnome-screensav          0        bcook       gnome-screensaver
 9745   642    dbus                     0        lp          /usr/lib/cups/notifier/dbus dbus://
 10337  1      sshd                     0        root        /usr/sbin/sshd -D
 10355  9237   update-notifier          0        bcook       update-notifier
 10370  1      jockey-backend           0        root        /usr/bin/python /usr/share/jockey/jockey-backend --debug -l /var/log/jockey.log
 10399  1      system-service-          0        root        /usr/bin/python /usr/lib/system-service/system-service-d
 10405  1      update-manager           0        bcook       /usr/bin/python /usr/bin/update-manager --no-focus-on-map
 10436  1      aptd                     0        root        /usr/bin/python /usr/sbin/aptd
 10733  10337  sshd                     0        root        sshd: bcook [priv]
 10916  10733  sshd                     0        bcook       sshd: bcook@notty
 11001  9625   server                   0        bcook       ./server


meterpreter > migrate 10355
[*] Migrating to 10355
[-] core_migrate: Operation failed: 1
meterpreter > migrate 10355
[*] Migrating to 10355
[*] Migration completed successfully.
meterpreter > migrate 9619
[*] Migrating to 9619
[*] Migration completed successfully.
meterpreter > sysinfo
Computer     : ubuntu
OS           : Linux ubuntu 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:50:54 UTC 2014 (i686)
Architecture : i686
Meterpreter  : x86/linux
```

**Pull request merged**
